# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='index',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
